FROM amazoncorretto:17-alpine-jdk

ARG JAR_FILE=build/libs/*.jar
ARG PROFILES
ARG ENV
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_JWT_ISSUER
ARG SPRING_JWT_SECRET_KEY
ARG OAUTH2_GOOGLE_CLIENT_ID
ARG OAUTH2_GOOGLE_CLIENT_SECRET
ARG OAUTH2_NAVER_CLIENT_ID
ARG OAUTH2_NAVER_CLIENT_SECRET
ARG OAUTH2_KAKAO_CLIENT_ID
ARG OAUTH2_KAKAO_CLIENT_SECRET
ARG AWS_SES_MAIL_USERNAME
ARG AWS_SES_MAIL_PASSWORD
ARG AWS_S3_BUCKET_NAME
ARG AWS_S3_ACCESS_KEY
ARG AWS_S3_SECRET_KEY
ARG NAVER_NEWS_CLIENT_ID
ARG NAVER_NEWS_CLIENT_SECRET
ARG OPEN_AI_KEY
ARG POAT_CORD
ARG POAT_KEY
ARG POAT_SECRET_KEY

ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV SPRING_JWT_ISSUER=$SPRING_JWT_ISSUER
ENV SPRING_JWT_SECRET_KEY=$SPRING_JWT_SECRET_KEY
ENV OAUTH2_GOOGLE_CLIENT_ID=$OAUTH2_GOOGLE_CLIENT_ID
ENV OAUTH2_GOOGLE_CLIENT_SECRET=$OAUTH2_GOOGLE_CLIENT_SECRET
ENV OAUTH2_NAVER_CLIENT_ID=$OAUTH2_NAVER_CLIENT_ID
ENV OAUTH2_NAVER_CLIENT_SECRET=$OAUTH2_NAVER_CLIENT_SECRET
ENV OAUTH2_KAKAO_CLIENT_ID=$OAUTH2_KAKAO_CLIENT_ID
ENV OAUTH2_KAKAO_CLIENT_SECRET=$OAUTH2_KAKAO_CLIENT_SECRET
ENV AWS_SES_MAIL_USERNAME=$AWS_SES_MAIL_USERNAME
ENV AWS_SES_MAIL_PASSWORD=$AWS_SES_MAIL_PASSWORD
ENV AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME
ENV AWS_S3_ACCESS_KEY=$AWS_S3_ACCESS_KEY
ENV AWS_S3_SECRET_KEY=$AWS_S3_SECRET_KEY
ENV NAVER_NEWS_CLIENT_ID=$NAVER_NEWS_CLIENT_ID
ENV NAVER_NEWS_CLIENT_SECRET=$NAVER_NEWS_CLIENT_SECRET
ENV OPEN_AI_KEY=$OPEN_AI_KEY
ENV POAT_CORD=$POAT_CORD
ENV POAT_KEY=$POAT_KEY
ENV POAT_SECRET_KEY=$POAT_SECRET_KEY

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-Dserver.env=${ENV}", "-jar", "app.jar"]
