spring:
  config:
    import: optional:env[.env]
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  address: 0.0.0.0
  port: 8080
  env: blue
